# Generated by Django 5.1.7 on 2025-10-16 19:57

import django.db.models.deletion
import predictor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(default=predictor.models.generate_signal_id, editable=False, max_length=30, unique=True)),
                ('asset', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=50)),
                ('impact_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
