# Generated by Django 5.1.7 on 2026-01-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_economiccalendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economiccalendar',
            options={'verbose_name': 'Economic Calendar', 'verbose_name_plural': 'Economic Calendar'},
        ),
    ]
