"""
Django settings for BinaryFusion project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f%1(c^j=rervgd5o@1qn4r#va)c4q#f@ywp++s4@*ojiplv-zx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'predictor',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- REQUIRED
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BinaryFusion.urls'

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BinaryFusion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'BinaryFusion',       # Your database name
        'USER': 'postgres.uyfypjkoudtjbeotrfas',           # Your PostgreSQL username
        'PASSWORD': 'gdeiDDcAF8U-**6',   # Your PostgreSQL password
        'HOST': 'aws-1-ap-northeast-1.pooler.supabase.com',        # Or the server IP
        'PORT': '5432',             # Default PostgreSQL port
        'OPTIONS': {'sslmode': 'require'},  # Added for Supabase compatibility
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Where collectstatic will put all static files for deployment
STATIC_ROOT = BASE_DIR / "staticfiles"

# # Compression and caching support for static files (Required for Render)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LOGIN_URL = '/accounts/login/'
# LOGIN_REDIRECT_URL = '/app/'  # After login, go to root (home)
# LOGOUT_REDIRECT_URL = '/accounts/login/'

LOGIN_URL = '/login/'  # Updated to match new login path
LOGIN_REDIRECT_URL = '/app/'  # Redirect to app.html after login
LOGOUT_REDIRECT_URL = '/login/'  # Redirect to login page after logout

# Add these to your settings.py
NOWPAYMENTS_API_KEY = '6FYMWZX-VTBMRY5-NTZCMJW-PGHV3NZ'
NOWPAYMENTS_IPN_SECRET = '224hR6qELB8ByjJUbqtn9DN7xrpYxOSH' # From Store Settings tab
NOWPAYMENTS_API_URL = 'https://api.nowpayments.io/v1/invoice' # Using Invoice for hosted page

NOWPAYMENTS_IPN_SECRET_SANDBOX = 'MMrDx78EfJTPPj4nJ2ZfOfRRjAOe5UuO6'