services:
  - type: web
    name: binaryfusion
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn BinaryFusion.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: WEB_CONCURRENCY
        value: 4