# Generated by Django 5.1.7 on 2025-10-16 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=10.0, help_text='Regular price for subscription (in USDT)', max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price for subscription (in USDT; optional)', max_digits=10, null=True)),
                ('is_discounted', models.BooleanField(default=False, help_text='If checked, the discounted price will be used as the effective price')),
            ],
            options={
                'verbose_name': 'Subscription Settings',
                'verbose_name_plural': 'Subscription Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('subscription', 'Subscription'), ('withdraw', 'Withdraw'), ('bonus', 'Bonus')], max_length=20)),
                ('currency', models.CharField(default='USDT', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('payment_method', models.CharField(default='Binance Pay', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_note', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text="User's balance in USDT", max_digits=10)),
                ('subscription', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
