# Generated by Django 5.1.7 on 2025-10-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_tokens',
            field=models.IntegerField(default=10, help_text='Maximum tokens allowed based on subscription'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=0, help_text="User's available tokens"),
        ),
    ]
