# Generated by Django 5.1.7 on 2025-10-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_max_tokens_profile_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Enable auto-renewal for premium subscription'),
        ),
    ]
