# Generated by Django 5.1.7 on 2025-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_auto_renew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auto_renew',
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_refill_tokens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_renew_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'System Default'), ('light', 'Light Mode'), ('dark', 'Dark Mode')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('EST', 'Eastern Time (EST/EDT)'), ('CST', 'Central Time (CST/CDT)'), ('MST', 'Mountain Time (MST/MDT)'), ('PST', 'Pacific Time (PST/PDT)'), ('GMT', 'London (GMT/BST)'), ('CET', 'Central European Time (CET/CEST)')], default='EST', max_length=10),
        ),
    ]
