# Generated by Django 5.1.7 on 2025-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_auto_renew_profile_auto_refill_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('subscription', 'Subscription'), ('withdraw', 'Withdraw'), ('bonus', 'Bonus'), ('refill', 'Refill')], max_length=20),
        ),
    ]
