# Generated by Django 5.1.7 on 2025-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_paymenthistory_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('subscription', 'Subscription'), ('withdraw', 'Withdraw'), ('bonus', 'Bonus'), ('refill', 'Token Refill')], max_length=20),
        ),
    ]
