# Generated by Django 5.1.7 on 2025-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_paymenthistory_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('partially_paid', 'Partially Paid')], default='pending', max_length=20),
        ),
    ]
