# Generated by Django 5.1.7 on 2026-03-05 12:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_instructions', tinymce.models.HTMLField(default='<p>Please follow these instructions to make a deposit.</p>', help_text='Edit the deposit instructions shown to users on the dashboard.')),
            ],
            options={
                'verbose_name': 'Site Content Setting',
                'verbose_name_plural': 'Site Content Settings',
            },
        ),
    ]
