# Generated by Django 5.1.7 on 2026-06-01 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_supportticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the partner platform (e.g., PocketOption)', max_length=100)),
                ('image', models.ImageField(help_text='Platform logo or image', upload_to='platforms/')),
                ('description', models.CharField(help_text='Short description of the platform', max_length=255)),
                ('affiliate_link', models.URLField(help_text='Your affiliate link for this platform')),
                ('is_highest_reward', models.BooleanField(default=False, help_text='Mark as Highest Reward')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide this platform on the dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner Platform',
                'verbose_name_plural': 'Partner Platforms',
                'ordering': ['-is_highest_reward', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('action_completed', models.CharField(choices=[('account_creation', 'Created New Account'), ('deposit', 'Made a Deposit')], max_length=20)),
                ('platform_uid', models.CharField(help_text="User's UID on the partner platform", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('earned_credit', models.CharField(blank=True, help_text='e.g., +50 USDT or -', max_length=50, null=True)),
                ('admin_remark', models.TextField(blank=True, help_text='Note from admin to user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_requests', to='accounts.partnerplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Request',
                'verbose_name_plural': 'Reward Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
