# Generated by Django 5.1.7 on 2026-06-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_partnerplatform_rewardrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerplatform',
            options={'ordering': ['-is_highest_reward', 'name'], 'verbose_name': 'Partner Platform', 'verbose_name_plural': 'Partner Platforms'},
        ),
        migrations.RemoveField(
            model_name='partnerplatform',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rewardrequest',
            name='action_completed',
        ),
        migrations.RemoveField(
            model_name='rewardrequest',
            name='admin_remark',
        ),
        migrations.AddField(
            model_name='partnerplatform',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partnerplatform',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo of the platform', null=True, upload_to='partner_logos/'),
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='action_type',
            field=models.CharField(choices=[('account_creation', 'Account Creation'), ('deposit', 'Deposit')], default='account_creation', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='remark',
            field=models.TextField(blank=True, help_text='Admin remarks shown to the user', null=True),
        ),
        migrations.AlterField(
            model_name='partnerplatform',
            name='affiliate_link',
            field=models.URLField(help_text='Affiliate registration link'),
        ),
        migrations.AlterField(
            model_name='partnerplatform',
            name='description',
            field=models.TextField(help_text='Short description displayed on the card'),
        ),
        migrations.AlterField(
            model_name='partnerplatform',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this platform from users'),
        ),
        migrations.AlterField(
            model_name='partnerplatform',
            name='is_highest_reward',
            field=models.BooleanField(default=False, help_text='Mark if this is the highest reward platform'),
        ),
        migrations.AlterField(
            model_name='partnerplatform',
            name='name',
            field=models.CharField(help_text='Name of the partner platform', max_length=100),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='earned_credit',
            field=models.CharField(default='-', help_text="e.g. '+50 USDT' or '-'", max_length=50),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.partnerplatform'),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
