# Generated by Django 5.1.7 on 2026-06-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_partnerplatform_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardrequest',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='rewardrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='PartnerPlatform',
        ),
        migrations.DeleteModel(
            name='RewardRequest',
        ),
    ]
